sudo: required
services:
  - docker
before_install:
  - docker build -t thomaslong/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true thomaslong/react-test npm test 
after_success:
  - docker build -t thomaslong/multi-client ./client
  - docker build -t thomaslong/multi-nginx ./nginx
  - docker build -t thomaslong/multi-server ./server
  - docker build -t thomaslong/multi-worker ./worker

