services:
  - docker
before_install:
  - docker build -t thomaslong/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true thomaslong/react-test npm test 
after_success:
  - docker build -t thomaslong/multi-client ./client
  - docker build -t thomaslong/multi-nginx ./nginx
  - docker build -t thomaslong/multi-server ./server
  - docker build -t thomaslong/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push thomaslong/multi-client
  - docker push thomaslong/multi-nginx
  - docker push thomaslong/multi-server
  - docker push thomaslong/multi-worker
# Deploy configuration
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"  # Replace with your AWS region
  app: "multi-docker-containers"  # Replace with your Elastic Beanstalk Application Name
  env: "multi-docker-containers-env"  # Replace with your Elastic Beanstalk Environment name
  bucket: "elasticbeanstalk-us-east-1-863198229499"  # Replace with your S3 bucket name
  bucket_path: "docker"  # Replace with your bucket path
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  on:
    branch: master  # Replace with the branch you want to deploy from

  