sudo: required
services:
  - docker
before_install:
  - docker build -t thomaslong/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true thomaslong/react-test npm test 
after_success:
  - docker build -t thomaslong/multi-client ./client
  - docker build -t thomaslong/multi-nginx ./nginx
  - docker build -t thomaslong/multi-server ./server
  - docker build -t thomaslong/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push thomaslong/multi-client
  - docker push thomaslong/multi-nginx
  - docker push thomaslong/multi-server
  - docker push thomaslong/multi-worker
  